/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as BoomRouteImport } from './routes/boom'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as MemoriesCreateRouteImport } from './routes/memories.create'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const BoomRoute = BoomRouteImport.update({
  id: '/boom',
  path: '/boom',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesCreateRoute = MemoriesCreateRouteImport.update({
  id: '/memories/create',
  path: '/memories/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boom': typeof BoomRoute
  '/welcome': typeof WelcomeRoute
  '/memories/create': typeof MemoriesCreateRoute
  '/memories': typeof MemoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boom': typeof BoomRoute
  '/welcome': typeof WelcomeRoute
  '/memories/create': typeof MemoriesCreateRoute
  '/memories': typeof MemoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boom': typeof BoomRoute
  '/welcome': typeof WelcomeRoute
  '/memories/create': typeof MemoriesCreateRoute
  '/memories/': typeof MemoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boom' | '/welcome' | '/memories/create' | '/memories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boom' | '/welcome' | '/memories/create' | '/memories'
  id:
    | '__root__'
    | '/'
    | '/boom'
    | '/welcome'
    | '/memories/create'
    | '/memories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoomRoute: typeof BoomRoute
  WelcomeRoute: typeof WelcomeRoute
  MemoriesCreateRoute: typeof MemoriesCreateRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boom': {
      id: '/boom'
      path: '/boom'
      fullPath: '/boom'
      preLoaderRoute: typeof BoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/': {
      id: '/memories/'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/create': {
      id: '/memories/create'
      path: '/memories/create'
      fullPath: '/memories/create'
      preLoaderRoute: typeof MemoriesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoomRoute: BoomRoute,
  WelcomeRoute: WelcomeRoute,
  MemoriesCreateRoute: MemoriesCreateRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
